name: Strofy
options:
  bundleIdPrefix: com.azawy
targets:
  Strofy:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIUserInterfaceStyle: Dark
      INFOPLIST_KEY_UIRequiresFullScreen: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
